import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BottomBar } from "@/features/bottomBar";
import { MSWProvider } from "@/shared/msw";
import { NextAuthProvider } from "@/features/kakaoLogin/index";

if (
  process.env.NEXT_RUNTIME === "nodejs" &&
  process.env.NODE_ENV !== "production"
) {
  const { server } = require("@/shared/msw/mock/http");
  server.listen();
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-dvw h-[92dvh]`}
      >
        <MSWProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
          <BottomBar />
        </MSWProvider>
      </body>
    </html>
  );
}
